# Generated by Django 5.1.1 on 2024-09-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="departure",
            field=models.DateField(),
        ),
    ]
