# Generated by Django 5.1.1 on 2024-09-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_alter_flight_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flight",
        ),
    ]
