# Generated by Django 5.1.1 on 2024-09-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("my_app", "0004_delete_flight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure", models.DateField()),
                ("sourcePlace", models.CharField(max_length=100)),
                ("destinationPlace", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
            ],
            options={
                "ordering": ["-departure"],
            },
        ),
    ]
