# Generated by Django 5.1.1 on 2024-09-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={},
        ),
    ]
